### ISSUE TITLE
Error at app.UseGleamTech(); in asp.net core after publish but working on the local development

### ISSUE THREAD

**Issue by imnkk** [GleamTech/FileUltimate#11]
Hi,

I have created a Asp.net Core application as specified at the URL- https://docs.gleamtech.com/fileultimate/html/using-fileultimate-in-an-asp-net-core-project.htm.

It's working on the local but when publishing it's throwing an error at the Startup.cs file -  app.UseGleamTech();

![Screenshot_20](https://user-images.githubusercontent.com/31114281/66315106-c12b7c80-e932-11e9-9d8e-78a3bb8733a7.png)

Please Help me. Thanks in advance.

My Startup.cs File code- 

 ```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();

            //Register GleamTech to the ASP.NET Core HTTP request pipeline.
            //----------------------
            app.UseGleamTech();
            //----------------------

            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseAuthentication();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

**Comment by GleamTech** [comment]
Did you skip step 3?

3. Open Startup.cs of your project.

Add GleamTech to the ASP.NET Core services container. Insert the marked line into the ConfigureServices method of your Startup.cs:

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc();


    //Add GleamTech to the ASP.NET Core services container.
    //----------------------
    services.AddGleamTech();
    //----------------------
}
```

**Comment by imnkk** [comment]
> Did you skip step 3?
> 
> 1. Open Startup.cs of your project.
> 
> Add GleamTech to the ASP.NET Core services container. Insert the marked line into the ConfigureServices method of your Startup.cs:
> 
> ```cs
> public void ConfigureServices(IServiceCollection services)
> {
>     services.AddMvc();
> 
> 
>     //Add GleamTech to the ASP.NET Core services container.
>     //----------------------
>     services.AddGleamTech();
>     //----------------------
> }
> ```

No, I did this also. I am attaching a doc file, along with startup.cs & program.cs as txt file, contains step by step details of - How I created project & configured things? Please have a look at it. Please help me. 
[FileUltimate in ASP.docx](https://github.com/GleamTech/FileUltimate/files/3701412/FileUltimate.in.ASP.docx)
[Program.txt](https://github.com/GleamTech/FileUltimate/files/3701424/Program.txt)
[Startup.txt](https://github.com/GleamTech/FileUltimate/files/3701425/Startup.txt)

**Comment by GleamTech** [comment]
Well, the problem seems to be the second step:

> Step 1 - created a project with ASP.NET Core 2.1 with .NET Framework
> Step 2 - **Installed Microsoft.AspNetCore.Session v2.0.2**
   Microsoft.AspNetCore - Already Installed
   Microsoft.AspNetCore.Mvc - Already Installed

Microsoft.AspNetCore 2.0.2 stated in the docs, is the minimum version but you have a project with ASP.NET Core 2.1 so you need to install the corresponding Microsoft.AspNetCore.Session 2.1.0 package:
https://www.nuget.org/packages/Microsoft.AspNetCore.Session/2.1.0

The reason that the error only happens on the server is probably that your server has ASP.NET Core 2.1 hosting runtime and it can't find v2.x DLLs.

**Comment by imnkk** [comment]
> Well, the problem seems to be the second step:
> 
> > Step 1 - created a project with ASP.NET Core 2.1 with .NET Framework
> > Step 2 - **Installed Microsoft.AspNetCore.Session v2.0.2**
> > Microsoft.AspNetCore - Already Installed
> > Microsoft.AspNetCore.Mvc - Already Installed
> 
> Microsoft.AspNetCore 2.0.2 stated in the docs, is the minimum version but you have a project with ASP.NET Core 2.1 so you need to install the corresponding Microsoft.AspNetCore.Session 2.1.0 package:
> https://www.nuget.org/packages/Microsoft.AspNetCore.Session/2.1.0
> 
> The reason that the error only happens on the server is probably that your server has ASP.NET Core 2.1 hosting runtime and it can't find v2.x DLLs.

Thanks for your help. But it did not work. Could you please give me a sample project which runs on the development as well as in the production mode, so that I can check it by running on our environment to fix the DLLs problems? 

I am attaching the list of the Software installed on my configured environment.
[Software List.xlsx](https://github.com/GleamTech/FileUltimate/files/3714027/Software.List.xlsx)


Thanks in advance.

**Comment by netsiddharth** [comment]
I'm also getting the same issue. 
@imnkk .. is it resolved?
Please help me.
Thanks in advance!

**Comment by GleamTech** [comment]
Are you using the latest version?
The example project is renamed to AspNetCoreOnNetFullCS and NuGet references are fixed:
https://github.com/GleamTech/FileUltimate/tree/master/Examples/AspNetCoreOnNetFullCS

This example project should work out of the box, we use the same for publishing to our demo site.

When publishing, ensure you have installed the corresponding version of  **Runtime & Hosting Bundle** to your target server from https://dotnet.microsoft.com/download/dotnet-core

![image](https://user-images.githubusercontent.com/13236524/68299437-8b240a00-0050-11ea-8f4d-d82f64253a04.png)

**Comment by GleamTech** [comment]
FYI, this issue is now fixed:
## Version 7.2.5 - November 13, 2019

 - **Fixed:** "Object reference not set to an instance of an object" error at app.UseGleamTech() line with ASP.NET Core 2.1 and 2.2 projects.
      Now ASP.NET Core 2.1 and 2.2 compatiblity is ensured.
