### ISSUE TITLE
get file path from UI

### ISSUE THREAD

**Issue by masgh021** [GleamTech/FileUltimate#14]
how get file url path
for use in website  ?
in UI menu , there is not property or path menu .

**Comment by Bam00001** [comment]
+
How can i get the each path after upload ?

**Comment by GleamTech** [comment]
It's in the docs:

Server side:
https://demos.gleamtech.com/fileultimate/AspNetCoreCS/#FileManager/ServerEvents
https://docs.gleamtech.com/fileultimate/html/E_GleamTech_FileUltimate_AspNet_UI_FileManager_Uploaded.htm

Client side:
https://demos.gleamtech.com/fileultimate/AspNetCoreCS/#FileManager/ClientEvents
https://docs.gleamtech.com/fileultimate/html/P_GleamTech_FileUltimate_AspNet_UI_FileManagerClientEvents_Uploaded.htm
