### ISSUE TITLE
Upload file that exceed quota limit

### ISSUE THREAD

**Issue by kata32** [GleamTech/FileUltimate#15]
If I apply a quota limit to a root folder and try to upload a file that exceeds the quota limit and also the chunk size, no warning over quota is returned and loaded chunks appear in the folder.

![2022-07-13_163955](https://user-images.githubusercontent.com/26146898/178761788-691911dd-1822-47cb-a11a-067696334853.png)

**Comment by GleamTech** [comment]
This should have been fixed in later versions.
