### ISSUE TITLE
Bug with Denied Permissions

### ISSUE THREAD

**Issue by jason-vetter-drasgow** [GleamTech/FileUltimate#17]
Here are 2 examples regarding access control permissions on a directory:
Note:  In these examples, AllowedPermissions is set to FileManagerPermissions.ReadOnly

#1: In the Preview pane, there is no Print button and there is no Download button.
AccessControl.DeniedPermissions = FileManagerPermissions.Download Or FileManagerPermissions.Copy Or FileManagerPermissions.Print

#2: In the Preview pane, there is a Print button and a Download button.
AccessControl.DeniedPermissions = FileManagerPermissions.Download Or FileManagerPermissions.Copy

There should not be a Print button in case #2.
It seems that when Print is available, download automatically becomes available.

**Comment by GleamTech** [comment]
That's not a bug, when you can print, it seems you can print to PDF in printer dialog, that's why download as PDF button is enabled. But download as original button will be disabled

**Comment by GleamTech** [comment]
FYI, with v9.1.0, we changed this behavior:

- Improved: Disabling FileManagerPermissions.Download permission will also disable DocumentViewerPermissions.DownloadAsPdf.
In the past we allowed DownloadAsPdf as the user could already print the document and save as PDF but it makes more sense
to disable it to prevent confusion as it has "Download" word in it.
So currently;
Disabling FileManagerPermissions.Download -> disables DocumentViewerPermissions.Download and DocumentViewerPermissions.DownloadAsPdf
Disabling FileManagerPermissions.Print -> disables DocumentViewerPermissions.Print and DocumentViewerPermissions.SelectText
