### ISSUE TITLE
Just upgraded licenses from 8.8.8 to 9.0.5 and receiving a "BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)" exception

### ISSUE THREAD

**Issue by DonWMason** [GleamTech/FileUltimate#18]
Receiving this error this morning after doing an Update_Package and buying a 9.0 license. The code worked fine for all 8.0 versions.

Switched to using your code sample from https://docs.gleamtech.com/fileultimate/html/using-fileultimate-in-an-asp-net-core-project.htm and still receiving the error below...

An unhandled exception occurred while processing the request.
BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
_6b+_fA+_f.Environment_Initialize()

TypeInitializationException: The type initializer for '_si' threw an exception.
_si._Hi(ImageFormat format)

TypeInitializationException: The type initializer for '_Wb' threw an exception.
_Wb._aD()

Stack Query Cookies Headers Routing
BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
_6b+_fA+_f.Environment_Initialize()
_6b+_l.Initialize()
_6b.Initialize()
_9e.Initialize()
_si._yI()
_si..cctor()

Show raw exception details
TypeInitializationException: The type initializer for '_si' threw an exception.
_si._Hi(ImageFormat format)
GleamTech.ImageUltimate.ImageFormatInfo._Hi()
GleamTech.ImageUltimate.ImageFormatInfo.SupportedFor(ImageFormatSupport formatSupport)
GleamTech.ImageUltimate.ImageFormatInfo.EnumerateExtensions(ImageFormatSupport formatSupport)+MoveNext()
_Wb._KB()
_Wb..cctor()

Show raw exception details
TypeInitializationException: The type initializer for '_Wb' threw an exception.
_Wb._aD()
_yb._ve()
GleamTech.FileUltimate.AspNet.FileUltimateWebConfiguration+_T._W(IDictionary<string, string> parameters)
GleamTech.AspNet.Resource.GetLastModifiedTimeUtc(IDictionary<string, string> parameters)
GleamTech.AspNet.ResourceBundle+_3G._Cl(Resource r)
System.Linq.Enumerable.Max<TSource, TResult>(IEnumerable<TSource> source, Func<TSource, TResult> selector)
GleamTech.AspNet.ResourceBundle.GetLastModifiedTimeUtc(IDictionary<string, string> parameters)
GleamTech.AspNet.ResourceManager.GetUrl(ResourceBundle resourceBundle, IDictionary<string, string> parameters)
GleamTech.FileUltimate.AspNet.UI.FileUploader.GetJsFileTags()
GleamTech.AspNet.UI.Component._MI()
GleamTech.AspNet.UI.Component._5T(bool withoutJs)
GleamTech.AspNet.UI.ComponentRenderer.RenderHead(TextWriter textWriter, Component component, bool withoutJs)
GleamTech.AspNet.UI.ComponentRenderer.RenderHead(Component component, bool withoutJs)
GleamTech.AspNet.Core.RazorPageExtensions.RenderHead(RazorPageBase razorPage, Component component, Component[] otherComponents)
AspNetCore.Areas_IntraNet_Views_MailOrders_MOFileManager+<>c__DisplayClass8_0+<<ExecuteAsync>b__0>d.MoveNext() in MOFileManager.cshtml
+
    @this.RenderHead(fileUploader)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
AspNetCore.Areas_IntraNet_Views_MailOrders_MOFileManager.ExecuteAsync() in MOFileManager.cshtml
+
    var fileUploader = new FileUploader
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
FMT.Net.Middleware.MaintenanceMiddleware.Invoke(HttpContext context) in MaintenanceMiddleware.cs
+
			await _next.Invoke(context);
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
ElmahCore.Mvc.ErrorLogMiddleware.InvokeAsync(HttpContext context)
ElmahCore.Mvc.ErrorLogMiddleware.InvokeAsync(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
FMT.Net.Middleware.FMTRedirectMiddleware.Invoke(HttpContext context) in FMTRedirectMiddleware.cs
+
			await _next.Invoke(context);
GleamTech.AspNet.Core.WebActivationMiddleware.Invoke(HttpContext context, IHostingEnvironment env)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
GleamTech.AspNet.Core.WebActivationMiddlewareExtensions._Iu(HttpContext context, Func<Task> next)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by GleamTech** [comment]
This is a native DLL error, likely it could not be overwritten

On your server (or wherever the error occurs) run “Command Prompt” as administrator
and type this command to reset IIS

`iisreset /restart`


If it's your development machine, close Visual Studio and kill any iisexpress.exe process if you see in the task bar

**Comment by DonWMason** [comment]
Rebooted PC, ran your command several times, open & closed VS - still an issue. What are the chances you're not supporting Win 11 ARM?

**Comment by GleamTech** [comment]
Ah that's the problem, only x86 or x64 are supported, ARM is a different architecture

**Comment by DonWMason** [comment]
Just went back to the older version and it didn't run on my dev machine but runs fine on my x64 Win IIS Servers.

Al lot of devs are moving to Win ARM devices. Are you planning to support us?

**Comment by GleamTech** [comment]
Good news, I have a fix for you, please try

**Version 9.0.6 - August 9, 2024**

> **Fixed:** Instead of thworing mysterious BadImageFormatException when loading native DLLs,
> FileUltimate should degrade gracefully until we support ARM architecture:
> 
> FileUltimate will work but it will just turn off the corresponding features such as generating image or video thumbnails or the document viewer.
