### ISSUE TITLE
ANGULAR SUPPORT

### ISSUE THREAD

**Issue by clydeburgos** [GleamTech/FileUltimate#6]
Hi,

We've been using the component from our old systems under ASP.NET Web forms and we're planning to migrate to Angular 5, would there be any support for that? do you guys have any plans for the UI Framework? Thanks!

**Comment by GleamTech** [comment]
Hi,
There is a sample project for using with Angular (it may be outdated but it can give you an idea):
www.gleamtech.com/downloads/t/WebAppAngularJS4.zip
